[project]
name = "iplotx"
description = "Plot networkx from igraph and networkx."
readme = "README.md"
dynamic = ["version"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "iplotx/version.py"
